import Head from 'next/head'
import { HeadLayout } from '../components/heads/HeadLayout'
import { AppLayout } from '../layouts/AppLayout'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <> 
      <HeadLayout title='News App' description='Generated by create next app' /> 
      <AppLayout>
        <Component {...pageProps} />
      </AppLayout>   
    </>
  )
}

export default MyApp
